name: app-container
services:
    backend:
        image: backend-app:latest
        container_name: backend-app
        restart: always
        build:
            context: ../
            dockerfile: Backend/Dockerfile
        environment:
            keySecretSettings: "/run/secrets/backend_secret_file"
        secrets:
            - backend_secret_file
    service:
        image: service-app:latest
        container_name: service-app
        restart: always
        build:
            context: ../
            dockerfile: Service/Dockerfile
        environment:
            keySecretSettings: "/run/secrets/service_secret_file"
        secrets:
            - service_secret_file
        ports:
            - 8093:8080  
     
secrets:
    backend_secret_file:
        file: ./BackendSecret.json
    service_secret_file:
        file: ./ServiceSecret.json
        