name: env-container
services:
    rabbitmq:
        image: rabbitmq:4.0-management
        hostname: rabbitmq
        restart: always
        environment:
          - RABBITMQ_DEFAULT_USER=rmuser
          - RABBITMQ_DEFAULT_PASS=rmpassword
          - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        volumes:
          - ./rabbitmq:/var/lib/rabbitmq
        ports:
          - 15672:15672
          - 5672:5672
      
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: 12345
        volumes:
          - pgdata:/var/lib/postgresql/data 
        ports:
          - 8091:5432
        
    adminer:
        image: adminer
        restart: always
        ports:
          - 8090:8090
 
volumes:
  pgdata: